# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9350f306bb871ad522a933b94ce5ae25a3e3dcd7976047c8ff4950390e578d8ba612a7ad27575055d0150aedd7e11e1e9be12bccd11d4723ef11df4662b7f89

test:
  secret_key_base: efb8a0642cf0e12fe43f4f0fde33a9127edf02308c7fbe1fc9599dd00ef11b960a317d576ef592e8a47d0421e7a7e0511cb3203a466c379f50ab0bfd3c5fa325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
